### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by HaveF** [fruitl00p/mongodb_consistent_backup-docker#1]
Thanks for this repo. could you tell me how to use it?

I see  [Percona-Lab/mongodb_consistent_backup: Tool for getting consistent backups from MongoDB Clusters and ReplicaSet](https://github.com/Percona-Lab/mongodb_consistent_backup#run-a-backup) says, do something like this:
`$ mongodb-consistent-backup -H mongos1.example.com -P 27018 -u mongodb-consistent-backup -p s3cr3t -n prodwebsite -l /opt/mongobackups`

but in  docker environment, when you start a container, you can not change the parameter passed to it. So the way to use it is to

1. create the container with parameters like the above? (use volume of course)
2. remove the container

next time, do the same thing again?  Do I understand it correctly?
Or do you have any good idea?

Thanks!

Btw, it seems the official docker image will be out,  [Dockerfile v1 by timvaillancourt · Pull Request #68 · Percona-Lab/mongodb_consistent_backup](https://github.com/Percona-Lab/mongodb_consistent_backup/pull/68)

**Comment by fruitl00p** [comment]
@HaveF Thanks! And yes, this this image predates the official docker movement of the repo :wink: 

The idea behind this image is indeed containerize the binary for running it... Thus the docker command would be something in the order of:
```
$ docker run gekkie/mongodb_consistent_backup -H mongos1.example.com -P 27018 -u mongodb-consistent-backup -p s3cr3t -n prodwebsite -l /opt/mongobackups
```
And you might want to volume-mount the `/opt/` into the container too... I did it more to contain all the dependencies than anything else ;)

**Comment by HaveF** [comment]
thanks!
